### ISSUE TITLE
unitialized constant Bumbler::Bundler on ruby 2.3.0

### ISSUE THREAD

**Issue by etagwerker** [nevir/Bumbler#12] opened 2016-04-26 13:40 UTC
I think there is a problem with Ruby 2.3.0 and Rails 3.2.18

This is what I'm getting: 

```
etagwerker:ombushop/ (develop✗) $ bumbler                                                                                                       /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:67:in `handle_require': uninitialized constant Bumbler::Bundler (NameError)
Did you mean?  Bumbler::Bundler
               Bundler
               Bumbler
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:34:in `block (2 levels) in hook_require!'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:67:in `handle_require'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:34:in `block (2 levels) in hook_require!'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/gems/bumbler-0.3.1/bin/bumbler:37:in `<top (required)>'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/bin/bumbler:23:in `load'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/bin/bumbler:23:in `<main>'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/bin/ruby_executable_hooks:15:in `eval'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.0@ombu/bin/ruby_executable_hooks:15:in `<main>'
```

It seems to work fine on ruby-2.2.4

**Comment by grosser** [comment] 2016-04-26 15:45
`Bundler::Bundler` is defined by an autoload in bumbler.rb

can you put a raise into lib/bumbler/bundler.rb and see if it gets loaded at all ?
next check if the bunbler.rb is loaded ...
then maybe put a Bumbler::Bundler right after the require in bin/bumbler:10 ... 
either autoload is broken or there is something funky going on ... maybe Bundler messing up the autoload ... try renaming Bunbler::Bundler to Bumbler::BundlerHelper ... that might fix it too ...

**Comment by grosser** [comment] 2016-04-26 15:45
via `bundle open bumbler`

**Comment by etagwerker** [comment] 2016-04-26 19:29
@grosser Sure, I'll check later and report back. Thanks!

**Comment by etagwerker** [comment] 2016-04-27 02:15
@grosser Interesting. This is what I found. `autoload` is not working. 

This doesn't seem to work: 

```
module Bumbler
  autoload :Bundler,  'bumbler/bundler'
  autoload :Hooks,    'bumbler/hooks'
  autoload :Progress, 'bumbler/progress'
  autoload :Stats,    'bumbler/stats'
  autoload :VERSION,  'bumbler/version'
end
```

However, if I change it to: 

```
module Bumbler
  require 'bumbler/bundler'
  require 'bumbler/hooks'
  require 'bumbler/progress'
  require 'bumbler/stats'
  require 'bumbler/version'
end
```

It works fine. 

Just curious, what are the benefits of using `autoload` vs. `require`? I found this issue: https://bugs.ruby-lang.org/issues/5653 but it seems to be quite old and I'm not sure if the deprecation

If you are interested, I can submit a PR switching to `require` - Let me know!

**Comment by grosser** [comment] 2016-04-27 02:20
the benefit of autoload is that it is faster / does not spend time
reading+parsing the files -> fast startup

for a library like bumbler maybe overkill ... but autoload should work ...
so let's not rewrite here just because some version of ruby is broken :)

On Tue, Apr 26, 2016 at 7:15 PM, Ernesto Tagwerker <notifications@github.com

**Comment by mauro-oto** [comment] 2016-04-27 13:19
@grosser @etagwerker it looks like changing `go.rb` from: 

```ruby
  Bundler.default_gemfile

  # Kick it off
  Bumbler::Hooks.hook_require!
  Bumbler::Hooks.watch_require!

  Bumbler::Bundler.start!
  Bumbler::Progress.start!
``` 

to: 

```ruby
  Bundler.default_gemfile

  # Kick it off
  Bumbler::Bundler
  Bumbler::Hooks.hook_require!
  Bumbler::Hooks.watch_require!

  Bumbler::Bundler.start!
  Bumbler::Progress.start!
```

fixes it for me using Ruby 2.3.0. I don't understand why or how exactly, but it seems to work so far for the 2 projects I tested it on.

**Comment by etagwerker** [comment] 2016-04-27 13:24
@grosser got it. I just ran a test with 2.3.1-p112 and I see the same behavior. 

```
etagwerker:ombushop/ (develop✗) $ bumbler
/Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:67:in `handle_require': uninitialized constant Bumbler::Bundler (NameError)
Did you mean?  Bumbler::Bundler
               Bundler
               Bumbler
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:34:in `block (2 levels) in hook_require!'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:67:in `handle_require'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/gems/bumbler-0.3.1/lib/bumbler/hooks.rb:34:in `block (2 levels) in hook_require!'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/gems/bumbler-0.3.1/bin/bumbler:37:in `<top (required)>'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/bin/bumbler:23:in `load'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/bin/bumbler:23:in `<main>'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/bin/ruby_executable_hooks:15:in `eval'
	from /Users/etagwerker/.rvm/gems/ruby-2.3.1@ombu/bin/ruby_executable_hooks:15:in `<main>'
etagwerker:ombushop/ (develop✗) $ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

@grosser I just tested @mauro-oto's solution in ruby-2.3.1 and it works for me.

**Comment by grosser** [comment] 2016-04-27 15:40
This bug will most likely impact a lot of projects, so I'd suggest we open
a ruby bug and give them something easy to reproduce.

On Wed, Apr 27, 2016 at 6:24 AM, Ernesto Tagwerker <notifications@github.com

**Comment by PikachuEXE** [comment] 2016-04-29 01:39
Can we workaround this bug (I guess it's a ruby bug)
by loading that file instead of autoloading?

**Comment by dmitry** [comment] 2016-04-29 09:19
@PikachuEXE https://github.com/nevir/Bumbler/issues/12#issuecomment-214948828

**Comment by PikachuEXE** [comment] 2016-04-29 09:41
@dmitry 
Sorry for not reading the whole thread 😁

**Comment by alvinkatojr** [comment] 2016-04-29 16:50
Removing the `-` in this line `export RUBYOPT=-rbumbler/go` and making it this: `export RUBYOPT=-rbumbler/go` in my shell file fixed it for me. Those errors are now gone and yet am running ruby 2.3.0

**Comment by alvinkatojr** [comment] 2016-04-29 16:56
Unfortunately the same error persists when am running brew commands and will likely persist in other area. My so called "fix" has n't solved anything in the long run. This seems to be a bug :(

**Comment by bquorning** [comment] 2016-05-08 19:15
Interesting that adding a `puts defined?(Bumbler::Bundler)` in lib/bumbler/hooks.rb:66 (right before the exception is raised) will reveals that `Bumbler::Bundler` is actually defined as a constant.

**Comment by grosser** [comment] 2016-05-08 21:05
Merged a nice clean fix submitted by @mauro-oto https://github.com/nevir/Bumbler/pull/13 ... ideally open an issue with ruby too ...

**Comment by grosser** [comment] 2016-05-08 21:13
0.3.2 is out!

**Closed by grosser** 2016-05-08 21:13 UTC

**Comment by willsu** [comment] 2016-12-02 22:37
@alvinkatojr Thank you! I'm using Ruby 2.2.3p173 and removing the dash from the `RUBY_OPTS` var fixed this issue for me: `RUBYOPT='rbumbler/go'`
